server:
  port: 8082

spring:
  application:
    name: hrms-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hrms_db
    username: ${DB_USERNAME:hrms_user}
    password: ${DB_PASSWORD:hrms_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  security:
    user:
      name: admin
      password: admin

# Kafka Configuration
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
  consumer:
    group-id: hrms-service
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    auto-offset-reset: earliest
    enable-auto-commit: false
    properties:
      spring.json.trusted.packages: "com.microservices.hrms.event"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10485760 # 10MB

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.microservices.hrms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/hrms-service.log

app:
  kafka:
    topic:
      user-registered: user-registered

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/hrms_db
    username: hrms_user
    password: hrms_password
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/